-- 20231218
SELECT GET_EMP_COUNT(10)
FROM DUAL;

SELECT DEPARTMENT_ID,
       DEPARTMENT_NAME,
       GET_EMP_COUNT(DEPARTMENT_ID) CNT
FROM DEPARTMENTS;

SELECT DEPARTMENT_ID,
       DEPARTMENT_NAME,
       GET_TOTAL_ANNUAL_SALARY(DEPARTMENT_ID)
FROM DEPARTMENTS;