// 1. TABLE1의 모든 행 조회
//   1) 오라클
SELECT *
FROM TABLE1 A, TABLE2 B
WHERE A.COLUMN = B.COLUMN(+);

//   2) ANSI
SELECT *
FROM TABLE1 A
LEFT OUTER JOIN TABLE2 B
ON A.COLUMN = B.COLUMN;



// 2. TABLE2의 모든 행 조회
//   1) 오라클
SELECT *
FROM TABLE1 A, TABLE2 B
WHERE A.COLUMN(+) = B.COLUMN;

//   2) ANSI
SELECT *
FROM TABLE1 A, TABLE2 B
RIGHT OUTER JOIN TABLE2 B
ON A.COLUMN = B.COLUMN;



// 3. TABLE1과 TABLE2의 모든 행 조회
//   1) 오라클은 FULL OUTER JOIN 허용X
SELECT *
FROM TABLE1 A, TABLE2 B
WHERE A.COLUMN(+) = B.COLOUMN(+);

//   2) ANSI는 가능
SELECT *
FROM TABLE1 A
FULL OUTER JOIN TABLE2 B
ON A.COLUMN = B.COLUMN;