-- 20231207

CREATE TABLE SAMPLE_PRODUCTS (
    PROD_NO             NUMBER(4) PRIMARY KEY,
    PROD_NAME           VARCHAR2(255) NOT NULL,
    PROD_MAKER          VARCHAR2(255),
    PROD_PRICE          NUMBER(7,0),
    PROD_DISCOUNT_PRICE NUMBER(7,0),
    PROD_STOCK          NUMBER(3,0),
    PROD_SOLD_OUT       CHAR(1) DEFAULT 'N',
    PROD_CREATED_DATE   DATE    DEFAULT SYSDATE,
    PROD_UPDATED_DATE   DATE    DEFAULT SYSDATE
);


INSERT INTO SAMPLE_PRODUCTS
(PROD_NO, PROD_NAME, PROD_MAKER, PROD_PRICE, PROD_DISCOUNT_PRICE, PROD_STOCK)
VALUES
(1, 'iphone15', 'apple', 150, 0.05, 20);

DELETE FROM SAMPLE_PRODUCTS
WHERE PRODUCT_NO = 2;


UPDATE SAMPLE_PRODUCTS
SET
    PROD_PRICE = 100,
    PROD_DISCOUNT_PRICE = 1,
    PROD_UPDATED_DATE = SYSDATE
WHERE
    PROD_NO = 2;